# Setup free domain with SSL for DocNhanh
Write-Host "DocNhanh - Free Domain Setup"
Write-Host "============================"
Write-Host ""

Write-Host "Current Status:"
Write-Host "✅ Backend running on: http://localhost:8000"
Write-Host "✅ API docs: http://localhost:8000/docs"
Write-Host "✅ Health check: http://localhost:8000/api/v1/health"
Write-Host ""

Write-Host "Free Domain Options:"
Write-Host ""

Write-Host "1. DUCKDNS (Recommended - Permanent domain):"
Write-Host "   🌐 Domain: https://docnhanh.duckdns.org"
Write-Host "   🔒 SSL: Auto from Let's Encrypt"
Write-Host "   📝 Steps:"
Write-Host "      a) Go to: https://www.duckdns.org/"
Write-Host "      b) Login with Google/GitHub"
Write-Host "      c) Create subdomain: docnhanh"
Write-Host "      d) Copy your token"
Write-Host "      e) Update docker-compose-with-domain.yml"
Write-Host "      f) Run: docker-compose -f docker-compose-with-domain.yml up -d"
Write-Host ""

Write-Host "2. NGROK (Quick - Temporary domain):"
Write-Host "   🌐 Domain: https://random-name.ngrok.io"
Write-Host "   🔒 SSL: Auto"
Write-Host "   📝 Steps:"
Write-Host "      a) Install: winget install --id ngrok.ngrok"
Write-Host "      b) Login: ngrok config add-authtoken YOUR_TOKEN"
Write-Host "      c) Run: ngrok http 8000"
Write-Host "      d) Copy the https URL from output"
Write-Host ""

Write-Host "3. SERVEO (No install needed):"
Write-Host "   🌐 Domain: https://serveo.net"
Write-Host "   🔒 SSL: Auto"
Write-Host "   📝 Steps:"
Write-Host "      a) Open PowerShell as Administrator"
Write-Host "      b) Run: ssh -R 80:localhost:8000 serveo.net"
Write-Host "      c) Copy the public URL"
Write-Host ""

Write-Host "4. CLOUDFLARE TUNNEL (Advanced):"
Write-Host "   🌐 Domain: Custom domain"
Write-Host "   🔒 SSL: Auto + Global CDN"
Write-Host "   📝 Steps:"
Write-Host "      a) Install: winget install --id Cloudflare.cloudflared"
Write-Host "      b) Login: cloudflared tunnel login"
Write-Host "      c) Create: cloudflared tunnel create docnhanh"
Write-Host "      d) Run: cloudflared tunnel run docnhanh"
Write-Host ""

Write-Host "Quick Test Commands:"
Write-Host "==================="
Write-Host ""

Write-Host "Test localhost:"
Write-Host "curl http://localhost:8000/api/v1/health"
Write-Host ""

Write-Host "Test with ngrok (if installed):"
Write-Host "ngrok http 8000"
Write-Host ""

Write-Host "Test with serveo:"
Write-Host "ssh -R 80:localhost:8000 serveo.net"
Write-Host ""

Write-Host "Choose your preferred method and follow the steps!"
Write-Host "All methods provide free SSL certificates automatically."
