# Simple domain setup with free SSL
Write-Host "Setting up DocNhanh with simple domain and SSL"
Write-Host "===============================================`n"

Write-Host "🌐 CÁC PHƯƠNG ÁN DOMAIN MIỄN PHÍ:"
Write-Host ""
Write-Host "1️⃣  DUCKDNS (Khuyến nghị - Đơn giản nhất):"
Write-Host "   ✅ Miễn phí hoàn toàn"
Write-Host "   ✅ SSL tự động từ Let's Encrypt"
Write-Host "   ✅ Cập nhật IP tự động"
Write-Host "   📝 Hướng dẫn:"
Write-Host "      - Truy cập: https://www.duckdns.org/"
Write-Host "      - Đăng nhập bằng Google/GitHub"
Write-Host "      - Tạo subdomain: docnhanh"
Write-Host "      - Copy token"
Write-Host "      - Domain sẽ là: https://docnhanh.duckdns.org"
Write-Host ""

Write-Host "2️⃣  CLOUDFLARE TUNNEL (Nâng cao):"
Write-Host "   ✅ Miễn phí + CDN toàn cầu"
Write-Host "   ✅ SSL tự động"
Write-Host "   ✅ Không cần port forwarding"
Write-Host "   📝 Hướng dẫn:"
Write-Host "      - Cài đặt: winget install --id Cloudflare.cloudflared"
Write-Host "      - Đăng nhập: cloudflared tunnel login"
Write-Host "      - Tạo tunnel: cloudflared tunnel create docnhanh"
Write-Host ""

Write-Host "3️⃣  NGROK (Nhanh nhất):"
Write-Host "   ✅ Setup trong 1 phút"
Write-Host "   ✅ SSL tự động"
Write-Host "   ❌ Domain thay đổi mỗi lần restart"
Write-Host "   📝 Hướng dẫn:"
Write-Host "      - Cài đặt: winget install --id ngrok.ngrok"
Write-Host "      - Đăng nhập: ngrok config add-authtoken YOUR_TOKEN"
Write-Host "      - Chạy: ngrok http 8000"
Write-Host ""

Write-Host "4️⃣  SERVEO (Không cần cài đặt):"
Write-Host "   ✅ Chạy trực tiếp từ browser"
Write-Host "   ✅ SSL tự động"
Write-Host "   📝 Hướng dẫn:"
Write-Host "      - Truy cập: https://serveo.net/"
Write-Host "      - Chạy: ssh -R 80:localhost:8000 serveo.net"
Write-Host ""

Write-Host "🚀 KHUYẾN NGHỊ:"
Write-Host "   - Cho production: DuckDNS + Traefik"
Write-Host "   - Cho testing: ngrok hoặc serveo"
Write-Host "   - Cho development: localhost"
Write-Host ""

Write-Host "📋 BƯỚC TIẾP THEO:"
Write-Host "   1. Chọn phương án phù hợp"
Write-Host "   2. Làm theo hướng dẫn"
Write-Host "   3. Cập nhật cấu hình"
Write-Host "   4. Chạy: docker-compose up -d"
Write-Host "   5. Truy cập domain của bạn"
